#include "buddy.h"
#include "idt.h"
#include "paging.h"

struct idt64 *idt64;

void isr_handler(u64 isr, struct isr_save_state save_state) {
    printf("FUCK");
    printf("ISR Number: %s\n", isr);
}

void setup_exception_table(){
    ASSERT(idt64 == 0, "IDT Table is not setup and should be setup");
    idt64[IDT_DIVIDE_ERROR] = IDT_TRAP_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_DIVIDE_ERROR));
    idt64[IDT_DEBUG] = IDT_TRAP_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_DEBUG));
    idt64[IDT_NMI_INTERRUPT] = IDT_INTR_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_NMI_INTERRUPT));
    idt64[IDT_BREAKPOINT] = IDT_TRAP_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_BREAKPOINT));
    idt64[IDT_OVERFLOW] = IDT_TRAP_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_OVERFLOW));
    idt64[IDT_BOUND_RANGE_EXCEEDED] = IDT_TRAP_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_BOUND_RANGE_EXCEEDED));
    idt64[IDT_INVALID_OPCODE] = IDT_TRAP_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_INVALID_OPCODE));
    idt64[IDT_DEVICE_NOT_AVAILABLE] = IDT_TRAP_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_DEVICE_NOT_AVAILABLE));
    idt64[IDT_DOUBLE_FAULT] = IDT_TRAP_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_DOUBLE_FAULT));
    idt64[IDT_COPROCESSOR_SEGMENT_OVERRUN] = IDT_TRAP_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_COPROCESSOR_SEGMENT_OVERRUN));
    idt64[IDT_INVALID_TSS] = IDT_TRAP_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_INVALID_TSS));
    idt64[IDT_SEGMENT_NOT_PRESENT] = IDT_TRAP_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_SEGMENT_NOT_PRESENT));
    idt64[IDT_STACK_SEGMENT_FAULT] = IDT_TRAP_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_STACK_SEGMENT_FAULT));
    idt64[IDT_GENERAL_PROTECTION_FAULT] = IDT_TRAP_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_GENERAL_PROTECTION_FAULT));
    idt64[IDT_PAGE_FAULT] = IDT_TRAP_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_PAGE_FAULT));
    idt64[IDT_RESERVED] = IDT_TRAP_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_RESERVED));
    idt64[IDT_X87_FLOATING_POINT_ERROR] = IDT_TRAP_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_X87_FLOATING_POINT_ERROR));
    idt64[IDT_ALIGNMENT_CHECK] = IDT_TRAP_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_ALIGNMENT_CHECK));
    idt64[IDT_MACHINE_CHECK] = IDT_INTR_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_MACHINE_CHECK));
    idt64[IDT_SIMD_FLOATING_POINT_ERROR] = IDT_TRAP_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_SIMD_FLOATING_POINT_ERROR));
    idt64[IDT_VIRTUALIZATION_EXCEPTION] = IDT_INTR_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_VIRTUALIZATION_EXCEPTION));
    idt64[IDT_CONTROL_PROTECTION_EXCEPTION] = IDT_INTR_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_CONTROL_PROTECTION_EXCEPTION));

    // Reserved exception vectors 22–31
    idt64[IDT_EXCEPTION_RESERVED_MIN] = IDT_TRAP_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_EXCEPTION_RESERVED_MIN));
    idt64[IDT_EXCEPTION_RESERVED_MAX] = IDT_TRAP_ENTRY((u64)EXCEPTION_ENTRY_PTR(IDT_EXCEPTION_RESERVED_MAX));
}

void init_idt(void) {
    idt64 = PAGE_TO_VIRT(allocate_page(PAGE_SIZE));
    setup_exception_table();
}
