TOOLCHAIN32 =  ../../toolchain/i686/bin
TOOLCHAIN64 =  ../../toolchain/x86_64/bin
CC32 = $(TOOLCHAIN32)/i686-elf-gcc
CC64 = $(TOOLCHAIN64)/x86_64-elf-gcc

CC := $(CC64)
OS := unix

all: 
	make -C acpica
